// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
//...
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbwrZrsuqxgV0so5hJXqM8B8GeKCGX7bs',
    appId: '1:8071909357:web:a82be6c2d5fe31ac0721e4',
    messagingSenderId: '8071909357',
    projectId: 'greencart60-14',
    authDomain: 'greencart60-14.firebaseapp.com',
    storageBucket: 'greencart60-14.firebasestorage.app',
    measurementId: 'G-FNWQY8CZTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNWmJc2iESeUSb5YXYvI5WtS81UYe_yYY',
    appId: '1:8071909357:android:8dd74127cc10e3db0721e4',
    messagingSenderId: '8071909357',
    projectId: 'greencart60-14',
    storageBucket: 'greencart60-14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIcbfbqacloMK2ht15NwNhIhASuTtXR7I',
    appId: '1:8071909357:ios:7a06c118d7d0c8820721e4',
    messagingSenderId: '8071909357',
    projectId: 'greencart60-14',
    storageBucket: 'greencart60-14.firebasestorage.app',
    iosBundleId: 'com.example.green',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIcbfbqacloMK2ht15NwNhIhASuTtXR7I',
    appId: '1:8071909357:ios:7a06c118d7d0c8820721e4',
    messagingSenderId: '8071909357',
    projectId: 'greencart60-14',
    storageBucket: 'greencart60-14.firebasestorage.app',
    iosBundleId: 'com.example.green',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbwrZrsuqxgV0so5hJXqM8B8GeKCGX7bs',
    appId: '1:8071909357:web:f6035e1d87c92c310721e4',
    messagingSenderId: '8071909357',
    projectId: 'greencart60-14',
    authDomain: 'greencart60-14.firebaseapp.com',
    storageBucket: 'greencart60-14.firebasestorage.app',
    measurementId: 'G-7Q6ECEV4Y0',
  );
}
